"use client";
import { useState } from "react";
import { formatInr, formatQuote, type Instrument, type Journal, type Review, type SimulatorSession } from "@/lib/simulator";
type Tab = "positions" | "orders" | "fills" | "journal" | "review";
export function ActivityPanel({ session, instrument, journal, review, onCancel, onAmend, onClose, onSaveJournal, onReview, simple = false }: { session: SimulatorSession; instrument?: Instrument; journal: Journal; review?: Review; onCancel: (id: string) => void; onAmend: (id: string, price: string) => void; onClose: (instrument: string, quantity: string) => void; onSaveJournal: (journal: Journal) => void; onReview: () => void; simple?: boolean }) {
  const [tab, setTab] = useState<Tab>("positions");
  const [showHistory, setShowHistory] = useState(false);
  const allOrders = session.orders;
  session = { ...session, positions: session.positions?.filter((position) => Number(position.quantity) !== 0), orders: showHistory ? allOrders : allOrders.filter((order) => order.status === "open") };
  const tabs: Tab[] = simple ? ["positions", "orders"] : ["positions", "orders", "fills", "journal", "review"];
  return <section className="activity"><nav aria-label="Activity tabs">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}<span>{item === "positions" ? session.positions?.length || 0 : item === "orders" ? session.orders.length : item === "fills" ? session.fills.length : ""}</span></button>)}</nav>
    <div className="activity-body">
      {tab === "orders" && <label className="history-toggle"><input type="checkbox" checked={showHistory} onChange={(event) => setShowHistory(event.target.checked)} /> Show completed and cancelled orders <span>Trade history is retained for your review.</span></label>}
      {tab === "positions" && <div className="table-wrap"><table><thead><tr><th>Instrument</th><th>Qty</th><th>Average</th><th>Market</th><th>Unrealized</th><th>Close</th></tr></thead><tbody>{session.positions?.map((position) => { const short = Number(position.quantity) < 0; return <tr key={position.instrument_id}><td>{position.instrument_id}</td><td>{position.quantity}</td><td>{formatQuote(position.average_price || position.avg_price, instrument?.quote_currency || "USD")}</td><td>{formatQuote(position.market_price, instrument?.quote_currency || "USD")}</td><td>{formatInr(position.unrealized_pnl || "0")}</td><td><button onClick={() => { const quantity = prompt(short ? "Quantity to cover" : "Quantity to close", String(Math.abs(Number(position.quantity)))); if (quantity) onClose(position.instrument_id, quantity); }}>{short ? "Cover" : "Close"}</button></td></tr>; })}</tbody></table>{!session.positions?.length && <p className="empty">No open positions.</p>}</div>}
      {tab === "orders" && <div className="table-wrap"><table><thead><tr><th>Side</th><th>Type</th><th>Qty</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{session.orders.map((order) => <tr key={order.id}><td className={order.side}>{order.side}</td><td>{order.order_type.replaceAll("_", " ")}</td><td>{order.quantity}</td><td>{formatQuote(order.limit_price || order.price, instrument?.quote_currency || "USD")}</td><td>{order.status}</td><td>{order.status === "open" && <><button disabled={!order.limit_price} onClick={() => { const price = prompt("New limit price", order.limit_price || ""); if (price) onAmend(order.id, price); }}>Amend</button><button onClick={() => onCancel(order.id)}>Cancel</button></>}</td></tr>)}</tbody></table>{!session.orders.length && <p className="empty">No orders yet.</p>}</div>}
      {tab === "fills" && <div className="table-wrap"><table><thead><tr><th>Order</th><th>Qty</th><th>Price</th><th>Fee</th></tr></thead><tbody>{session.fills.map((fill) => <tr key={fill.id}><td>{fill.order_id}</td><td>{fill.quantity}</td><td>{formatQuote(fill.price, instrument?.quote_currency || "USD")}</td><td>{formatInr(fill.fee)}</td></tr>)}</tbody></table>{!session.fills.length && <p className="empty">No fills yet.</p>}</div>}
      {tab === "journal" && <JournalEditor key={`${journal.updated_at || ""}:${journal.plan}:${journal.reflection}`} journal={journal} onSave={onSaveJournal} />}
      {tab === "review" && <div className="review">{review ? <><strong>{review.score}/100 · {review.passed ? "Passed" : "Not passed"}</strong>{Object.entries(review.dimensions).map(([name, value]) => <p key={name}>{name.replaceAll("_", " ")} <span>{value}</span></p>)}{review.evidence?.map((item) => <small key={item.rule}>{item.passed ? "✓" : "!"} {item.rule.replaceAll("_", " ")}</small>)}{review.ai_review && !review.ai_review.available && <small>{review.ai_review.reason}</small>}</> : <><p>Generate the saved session review from the API.</p><button className="primary" onClick={onReview}>Get review</button></>}</div>}
    </div>
  </section>;
}
function JournalEditor({ journal, onSave }: { journal: Journal; onSave: (journal: Journal) => void }) {
  const [notes, setNotes] = useState(journal);
  return <div className="journal"><label>Trade plan<textarea value={notes.plan} onChange={(event) => setNotes({ ...notes, plan: event.target.value })} /></label><label>Reflection<textarea value={notes.reflection} onChange={(event) => setNotes({ ...notes, reflection: event.target.value })} /></label><button className="primary" onClick={() => onSave(notes)}>Save journal</button></div>;
}
