"use client";

import { useEffect, useMemo, useState } from "react";
import { simulatorApi, formatInr, type Instrument, type SimulatorSession } from "@/lib/simulator";

export default function TradePage() {
  const [instruments, setInstruments] = useState<Instrument[]>([]); const [session, setSession] = useState<SimulatorSession | null>(null);
  const [layout, setLayout] = useState<"beginner" | "advanced">("beginner"); const [mode, setMode] = useState<"replay" | "delayed">("replay");
  const [side, setSide] = useState<"buy" | "sell">("buy"); const [quantity, setQuantity] = useState("1"); const [plan, setPlan] = useState(""); const [reflection, setReflection] = useState("");
  const [review, setReview] = useState<{ score: number; passed: boolean; assisted: boolean } | null>(null); const [error, setError] = useState("");
  useEffect(() => { Promise.all([simulatorApi.instruments(), simulatorApi.bootstrap()]).then(([list]) => setInstruments(list)).catch((e) => setError(e.message)); }, []);
  const selected = instruments[0]; const price = useMemo(() => session?.orders[0]?.price || "—", [session]);
  async function start() { if (!selected) return; try { setError(""); setReview(null); setSession(await simulatorApi.createSession(mode, selected.id)); } catch (e) { setError(e instanceof Error ? e.message : "Could not start practice."); } }
  async function refresh(next: Promise<SimulatorSession>) { try { setSession(await next); } catch (e) { setError(e instanceof Error ? e.message : "Action failed."); } }
  async function submitOrder() { if (!session) return; try { await simulatorApi.order(session.id, { side, order_type: "market", quantity }); setSession(await simulatorApi.getSession(session.id)); } catch (e) { setError(e instanceof Error ? e.message : "Order failed."); } }
  if (error) return <main className="mx-auto max-w-3xl p-8"><h1 className="text-2xl font-bold">Practice trading</h1><p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</p></main>;
  if (!session) return <main className="mx-auto max-w-5xl p-5 sm:p-10"><p className="text-sm font-semibold text-blue-600">ChartCoach practice</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Practice the process, not predictions.</h1><p className="mt-3 max-w-2xl text-slate-600">Use synthetic testing data in historical replay or a 15-minute delayed practice account. Virtual funds only.</p><div className="mt-8 grid gap-4 md:grid-cols-2"><button onClick={() => setMode("replay")} className={`rounded-2xl border p-6 text-left ${mode === "replay" ? "border-blue-600 bg-blue-50" : "border-slate-200"}`}><strong>Historical replay</strong><span className="mt-2 block text-sm text-slate-600">Control the clock, place trades, and fork a fresh assisted attempt when rewinding.</span></button><button onClick={() => setMode("delayed")} className={`rounded-2xl border p-6 text-left ${mode === "delayed" ? "border-blue-600 bg-blue-50" : "border-slate-200"}`}><strong>Delayed paper trading</strong><span className="mt-2 block text-sm text-slate-600">Persistent virtual account using a labeled 15-minute delayed clock.</span></button></div><button disabled={!selected} onClick={start} className="mt-6 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white disabled:opacity-50">Start {mode === "replay" ? "replay" : "delayed practice"}</button></main>;
  return <main className="min-h-screen bg-slate-950 p-3 text-slate-100 sm:p-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-blue-300">{mode === "replay" ? "Replay · Synthetic test data" : "Delayed practice · Synthetic test data"}</p><h1 className="text-xl font-bold">{session.instrument_id}</h1></div><div className="flex gap-2"><button onClick={() => setLayout(layout === "beginner" ? "advanced" : "beginner")} className="rounded-lg border border-slate-700 px-3 py-2 text-sm">{layout === "beginner" ? "Advanced layout" : "Beginner layout"}</button><div className="rounded-lg bg-slate-800 px-3 py-2 text-sm">Equity {formatInr(session.account.equity)}</div></div></header><div className={`mt-4 grid gap-4 ${layout === "advanced" ? "lg:grid-cols-[220px_minmax(0,1fr)_280px]" : "lg:grid-cols-[minmax(0,1fr)_300px]"}`}>
    {layout === "advanced" && <aside className="rounded-xl bg-slate-900 p-3"><p className="text-xs font-semibold text-slate-400">WATCHLIST</p>{instruments.slice(0, 8).map((item) => <div className="mt-3 text-sm" key={item.id}>{item.symbol}<span className="float-right text-slate-400">{item.venue}</span></div>)}</aside>}
    <section className="rounded-xl bg-slate-900 p-4"><div className="flex flex-wrap gap-2"><button onClick={() => refresh(simulatorApi.control(session.id, "step"))} className="rounded bg-blue-600 px-3 py-2 text-sm">Step +1m</button><button onClick={() => refresh(simulatorApi.control(session.id, session.state === "playing" ? "pause" : "play"))} className="rounded bg-slate-700 px-3 py-2 text-sm">{session.state === "playing" ? "Pause" : "Play"}</button>{[1,5,20].map((speed) => <button onClick={() => refresh(simulatorApi.control(session.id,"speed",speed))} className="rounded bg-slate-800 px-2 py-2 text-xs" key={speed}>{speed}×</button>)}<button onClick={() => refresh(simulatorApi.control(session.id,"fork"))} className="rounded bg-amber-600 px-3 py-2 text-sm">Fork attempt</button></div><div className="mt-4 flex h-80 items-end gap-px rounded-lg bg-slate-950 p-4" aria-label="Synthetic candlestick chart">{Array.from({length:45},(_,i)=><i key={i} className={`w-full rounded-sm ${i%3 ? "bg-emerald-400" : "bg-rose-400"}`} style={{height:`${22+(i*17)%70}%`}} />)}</div><p className="mt-3 text-xs text-slate-400">1-minute execution · current simulated minute {session.clock} · future candles hidden</p></section>
    <aside className="space-y-4"><section className="rounded-xl bg-slate-900 p-4"><h2 className="font-semibold">Order ticket</h2><div className="mt-3 flex gap-2"><button onClick={()=>setSide("buy")} className={`flex-1 rounded p-2 ${side==="buy"?"bg-emerald-600":"bg-slate-800"}`}>Buy</button><button onClick={()=>setSide("sell")} className={`flex-1 rounded p-2 ${side==="sell"?"bg-rose-600":"bg-slate-800"}`}>Sell</button></div><label className="mt-3 block text-xs text-slate-400">Quantity<input value={quantity} onChange={e=>setQuantity(e.target.value)} className="mt-1 w-full rounded bg-slate-800 p-2 text-white" inputMode="decimal" /></label><button onClick={submitOrder} className="mt-3 w-full rounded bg-blue-600 p-2 font-semibold">Place market order</button><p className="mt-2 text-xs text-slate-400">Fees, spread, and slippage are educational test preset values.</p></section><section className="rounded-xl bg-slate-900 p-4"><h2 className="font-semibold">Journal</h2><textarea value={plan} onChange={e=>setPlan(e.target.value)} placeholder="Trading plan" className="mt-2 w-full rounded bg-slate-800 p-2 text-sm" /><textarea value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="Post-trade reflection" className="mt-2 w-full rounded bg-slate-800 p-2 text-sm" /><button onClick={async()=>{await simulatorApi.journal(session.id,plan,reflection);setReview(await simulatorApi.review(session.id));}} className="mt-2 rounded bg-slate-700 px-3 py-2 text-sm">Save and score</button>{review&&<p className="mt-2 text-sm">Process score: <b>{review.score}/100</b>{review.assisted?" · assisted attempt":""}</p>}</section></aside>
  </div><section className="mt-4 rounded-xl bg-slate-900 p-4"><h2 className="font-semibold">Orders & fills</h2>{session.orders.length ? <div className="mt-2 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-400"><tr><th>Side</th><th>Type</th><th>Qty</th><th>Price</th><th>Status</th></tr></thead><tbody>{session.orders.map(o=><tr key={o.id}><td>{o.side}</td><td>{o.order_type}</td><td>{o.quantity}</td><td>{o.price}</td><td>{o.status}</td></tr>)}</tbody></table></div>:<p className="mt-2 text-sm text-slate-400">No orders yet. Current fill price will be simulated from the next eligible minute.</p>}</section></main>;
}
